name: Post Issue Comment
author: Alexander Thoukydides
description: Post a comment to an issue and minimise any previously added comments (as OUTDATED)
branding:
  icon: 'at-sign'
  color: 'blue'

inputs:
  issue_number:
    description: The GitHub issue to comment on
    required: true
    type: number
  body:
    description: The comment body to add
    required: true
    type: string
  marker:
    description: A prefix for the comment body, used to identify previous comments to be minimised
    type: string
    default: '<!-- bot-comment -->'
  github_token:
    description: The GitHub token used to create an authenticated client
    type: string
    default: ${{ github.token }}
  dry_run:
    description: Disables actions that modify the issue (adding the comment and minimising previous comments) for testing
    type: boolean
    required: false

runs:
  using: node20
  main: dist/index.js